name: matrix

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  #build:
    # The type of runner that the job will run on
  run_pipeline_tests_with_multiple_tf_version:
    strategy:
      matrix:
        version: [0.14.7, 1.1.7]
    runs-on: ubuntu-22.04
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.version }}
      - name: run pipeline-tests
        run: echo running pipeline tests
     