name: terraform setup dynamically
on: 
  workflow_call:
    inputs:
      tf_version: 
        description: the tf version
        required: false
        default: 0.14.7
        type: string
    
jobs:
  setup_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version:  ${{ inputs.tf_version }}
    
