name: use-reuse-workflow

#what could be the trigger
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main,master ]
  
  workflow_dispatch:

#   A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download_dependencies:
    runs-on: ubuntu-latest
    uses: ./github/workflows/reusable-workflow.yml
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: deploy job
        run: echo deploy job